### ISSUE TITLE
Grabbing Fireteam

### ISSUE THREAD

**Issue by DemonDhampir** [SteffanLong/DestinyTrialsReport#84]
I've noticed a few times, in the previous build, and the current, when entering a person's name, it sometimes misses a Guardian or doesn't grab any of the fireteam, and only the entered player's Guardian.
Also, I haven't yet come across this in the current Live build, but it happened in the previous build, the "Currently Equipped" Things we're completely wrong, even sometimes was grabbing the complete wrong Character, i.e; The Player would be using a Warlock, and it would show a Titan.
Hope this information helps, and I hope you can figure out what causes these problems, as i really enjoy the entire idea for this, and other than these few issues i've come across, it works really well.
Thanks,
Demon Dhampir

**Comment by v-fedorov** [comment]
The currently equipped and wrong character issue was fixed in the current build.

The first one could be two things,
- If a person has no trials history then we have no way to determine who is on the fireteam.
- We're working on optimizing our api server but sometimes(rarely) it hangs causing only the first searched guardian to be returned.

Thanks for the support! :)
